<div align ="right">Thomas Jefferson University **COMP 102**: Intro to Scientific Computing</div>

## Data structures with numpy

In this worksheet we will work on creating data structures with numpy. Oftentimes when we are doing scientific computing one of our biggest challenges has to do with working with the data set we are given. That can mean lots of different things. Arranging data, summarizing data, dealing with incomplete observations. But before we can do any of that, we have to get our data into some kind of structure. 

Numpy (The name comes from **Num**eric **py**thon) is a library for python that contains many powerful functions for working with data. The principal data structure we will deploy is a structure called a **numpy array**.

To work with any python library, we first need to import that library into our workspace. This allows us to access any functions or other elements contained within that library as if we defined them ourselves as part of our python script.

In [1]:
import numpy as np

Once you have run the code above, we will have access to numpy's functions. Note that we created a shorthand for the function - so we can refer to it as np, and can call any function contained within the library by using a command of the form: 
``` 
np.function_name()
```
In the command below, we will use the numpy function `zeros()` to create an empty numpy array with a single dimension. This array will hold five pieces of data which the function will fill with zeros.

In [2]:
v = np.zeros(5)
print(v) 

[0. 0. 0. 0. 0.]


Note that numpy is fundamentally a system for holding and performing mathematical operations on numerical data, so the data added to a numpy array will be set to the type `float64` by default. Note that the function can be indexed just like a list. We can change the values in the array by assigning a value to a position in the array designated by its index.

In [3]:
print(type(v[0]))      # Figure out and report what the data type of each element is

v[0]=6.5               # Substitute a different value for the first item in the array
print(v)


<class 'numpy.float64'>
[6.5 0.  0.  0.  0. ]


In [4]:
v[3]= "banana"  

ValueError: could not convert string to float: 'banana'

Try running the code above - unlike a list, if we add different kinds of data to a numpy array we will get an error. 

The following code uses a new numpy function, `ones` , the output should not surprise you. 

In [5]:
w = np.ones(6)
print(w)

[1. 1. 1. 1. 1. 1.]


We can also use the numpy function `array` in a couple of different ways. First, we can use it to define an array manually by putting square brackets, as if we were defining a list, inside the parentheses of the numpy function:


Numpy arrays can be defined with more than one dimension.    to create a one dimensional array (which you might call a matrix)

In [6]:
manual_array = np.array([1.735, 3.14, 2.89, 7.5])
print(manual_array)

[1.735 3.14  2.89  7.5  ]


Likewise, we can convert a `list` to a numpy array by using it as the input to the `array` function. 

In [ ]:
list_to_convert = [42.3, 74.1, 89.3, 100.2]
print(type(list_to_convert))                   

converted_list = np.array(list_to_convert)
print(type(converted_list))

Numpy arrays have certain characteristics that allow them to be useful for data manipulation. One of them is that every numpy array has an attribute known as `shape`. We have already used shapes. When we defined our intial numpy array above, we told numpy to create an array with shape 5. 

In [7]:
print(v.shape)

(5,)


This notation means that the shape of the array is one dimensional, with a length of five. We can also use the `shape` command to change the shape of a data structure. 

In [8]:
x = np.ones(24)
print("old shape " + str(x.shape))   # report the shape
print(x)

x.shape = (4,6)                      # now let's change the shape
print("new shape " + str(x.shape))   # report the new shape
print(x)

old shape (24,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
new shape (4, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


We can also use the shape function when we define the function in the first place, just note that for any array with more than one diemension the shape specfication must be enclosed in parentheses, even within the call to the array making function (`ones` in this case)
Also, when we index data, we now need to use both dimensions in the specification of which datapoint we are talking about. 

In [9]:
w = np.ones((6,6))
print("original array")
print(w)

w[0,0] = 0
w[5,5] = 8
print("array with substitutions")
print(w)

original array
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
array with substitutions
[[0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 8.]]


Just like a list, the indices of an array will count from 0, so an array of length 6 will consist of positions 0 through 5. Practice changing the code above until you are confident that you could drop a value down into an array. 

Try to run the next two pieces of code on array w and intrepret the IndexError and Value Error statements that result.

Can you change the parameters so that each one works???

In [10]:
w[6,6]


IndexError: index 6 is out of bounds for axis 0 with size 6

In [11]:
w.shape = (4,4)  
w

ValueError: cannot reshape array of size 36 into shape (4,4)

Another very handy thing to do with numpy is to create arrays that have even spacing. the command `linspace` = linear spaced which means that variables in the array are spaced out linearly. Run the code, then change it so that it counts by 10 instead of by 5. 

In [12]:
z = np.linspace(0,100,21)
z

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

## Importing data with numpy
Ok, we can see that these array data structures are going to be a lot more powerful than just working with text files. In fact, numpy comes with a function that allows us to read directly from text. It's called `genfromtxt` meaning "generate a numpy array from a text file". Try the code below

In [13]:
Gradebook_array = np.genfromtxt("data/Gradebook.csv")
print(Gradebook_array)


[nan nan nan nan nan nan]


Hmmm, this doesn't look right. What else might we need to do? It turns out that with numpy, we need to give it more information when it is dealing with a text file. We can do this by specifying a `delimiter`, in this case `,`

In [14]:
Gradebook_array = np.genfromtxt("data/Gradebook.csv", delimiter =',', skip_header=True)
print(Gradebook_array)


[[ nan  89.  92.  93.  95.]
 [ nan  92.  91.  94.  95.]
 [ nan  75.  77.  72.  97.]
 [ nan  82.  86.  88.  85.]
 [ nan  85.  91.  83. 100.]]


Aha, that looks better. But what are the `nan` values? They signify no data! Of course, numpy can only handle numerical data, so we end up with an organized data table, but none of the associated text. We would have to harvest that information from our `.csv` file in a different way and keep track of those arrays separately. That's not great, which is why we will learn the next tool in the scientific computing toolbox, pandas. 